[nextjs-react] Update to use @ syntax for remotes
module-federation/module-federation-examples pull request #2067
Opened 2022-07-09 17:22 UTC by JohnDaly

## Changes
- Updating `nextjs-react` example to use the @ syntax for remotes
- Updating `nextjs-react` example to use `yarn` instead of `npm`. 
  - There was mixed usage of both in this example. I opted for `yarn` because it is used in more examples throughout the monorepo

## Other Fixes
- Adding `.npmrc` file to set privjs as registry for `@module-federation` packages
- Updating ESLint config in `nextjs-react/host-app` to fix linter warnings about `next/babel`
- Updating `webpack-cli` to fix `TypeError: cli.isMultipleCompiler is not a function` error
- Updating `webpack` and `webpack-dev-server` to latest versions

2022-07-09 17:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/module-federation/module-federation-examples?pullRequest=2067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/module-federation/module-federation-examples?pullRequest=2067) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/module-federation/module-federation-examples?pullRequest=2067) it.</sub>

2022-07-09 17:28 UTC, JohnDaly commented on nextjs-react/remote-app/package.json
> +    "webpack-cli": "4.10.0",
Fixes:

```
[0] [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
[0]     at Command.<anonymous> (/module-federation-examples/nextjs-react/remote-app/node_modules/@webpack-cli/serve/lib/index.js:146:35)
[0]     at async Promise.all (index 1)
[0]     at async Command.<anonymous> (/module-federation-examples/nextjs-react/remote-app/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)
```

2022-07-09 17:28 UTC, JohnDaly commented on nextjs-react/host-app/.eslintrc.json
> +  "extends": ["next/babel", "next/core-web-vitals"]
Fixes the `Parsing error: Cannot find module 'next/babel'` error from ESLint

2022-07-11 02:56 UTC, ScriptedAlchemy requested changes
Please check the v4 release for nextjs-mf 

The api has changed slightly. No need to double configure MFP on next apps. All is done with the sidecar. Ideally I'd use the new major release if you're moving to the @ syntax

2022-07-11 05:30 UTC, JohnDaly commented
> Please check the v4 release for nextjs-mf
> 
> The api has changed slightly. No need to double configure MFP on next apps. All is done with the sidecar. Ideally I'd use the new major release if you're moving to the @ syntax

I've updated to the v4 release and updated the Next.js host app in the example to use `withFederatedSidecar` in https://github.com/module-federation/module-federation-examples/pull/2067/commits/ec84bdf38e1743a11fe20db03d0055ad29ee078d

2022-07-11 08:06 UTC, ScriptedAlchemy commented
Perfect. Will review tomorrow morning

2022-07-16 15:51 UTC, JohnDaly commented
@ScriptedAlchemy do the changes look good to you?

2022-07-16 17:09 UTC, merged