feat: Federating CSS/scss
module-federation/module-federation-examples pull request #2577
Opened 2023-01-05 14:19 UTC by belinef

2023-01-05 20:52 UTC, ScriptedAlchemy commented
let me know when this is out of draft status

2023-01-12 16:03 UTC, edchai requested changes

2023-01-12 16:03 UTC, edchai commented on cypress/common/selectors.ts
> +    dataE2e: '[data-e2e]'
please check how we already added  e2e selectors, point of it in it's uniqueness , not just e2e

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkApp1.cy.ts
> +function getButtonCompareConfig(n: number, color: string): {
functions should not be created in the same file as tests. Please check how we already did this and read https://github.com/module-federation/module-federation-examples/pull/2596

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkApp1.cy.ts
> +    it('Check elements exist', () => {
Name of the test is not correspond with methods in it. Please provide less vague and more correspond name

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkApp1.cy.ts
> +
remove blankline

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +function getButtonCompareConfig(section: number, btnNumber: number, color: string): {
same comment as above. Also no need for redeclare almost exact method

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +        selector: `${baseSelectors.section}:nth-of-type(${section})`,
no need to get selector as css type. If you need dynamic selector better to create dynamic e2e

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +
remove blankline

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +    it('Check elements exist', () => {
same as above

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +        basePage.checkElementVisibility(`${baseSelectors.section}:nth-of-type(1)`);
same as above

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +
remove blankline

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +        basePage.checkChildElementHaveProperty(getButtonCompareConfig(1, 1, Constants.color.absoluteBlack));
not quite sure what you did here with indexes, better to find more readable way

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +    it('Check workaround off', () => {
Please less vague name

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +        basePage.checkElementVisibility(`${baseSelectors.section}:nth-of-type(2)`);
same as above

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +
remove blankline

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +        basePage.checkChildElementHaveProperty(getButtonCompareConfig(2, 1, Constants.color.absoluteBlack));
same as above

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +    it('Check workaround on', () => {
same as above

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +        cy.get(`${baseSelectors.section}:nth-of-type(2)`)
no need to redeclare it here, we already have base methods for click which you can call

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +        basePage.checkChildElementHaveProperty(getButtonCompareConfig(2, 1, Constants.color.absoluteBlack));
same as above

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/helpers.ts
> +  return `${selectors.dataE2e}:nth-child(${n})`;
This could be reworked if you will create proper e2e selector, also it belongs to sample->e2e->methods, check as we did it before with methods.ts

2023-01-12 16:03 UTC, edchai commented on federated-css/e2e/checkNextJsApp.cy.ts
> +        basePage.checkChildElementHaveProperty(getButtonCompareConfig(2, 9, Constants.color.absoluteBlue));
please check commonChecks conception. Your checks almost similar, so you can combine it and parse with forEach

2023-01-17 14:26 UTC, edchai requested changes

2023-01-17 14:26 UTC, edchai commented on cypress/common/selectors.ts
> +    federatedCssButton: '[data-e2e="federated-css-button"]'
please name of e2e in uppercase with _ , not -, check other examples

2023-01-17 14:26 UTC, edchai commented on federated-css/e2e/checkNextCombinationOf4.cy.ts
> +    it('should verify consumed scss page', () => {
I think something should be changed here. If you name test something like 'should verify exposed buttons colors' as you did, it's clearly understandable what is going on, but this name and similar ones is not. Try to change names to more understandable

2023-01-17 14:26 UTC, edchai commented on federated-css/e2e/checkReactTailwindModuleAndJss.cy.ts
> +    });
as I understand you have almost similar checks which differs only by port. If I right please open any commonChecks.cy.ts file and check how we can handle common tests with usage of forEach. It's very likely that your tests would become much smaller with this approach

2023-01-18 14:07 UTC, edchai requested changes

2023-01-18 14:07 UTC, edchai commented on federated-css/e2e/constants.ts
> +export const ExposedButtons = {
why create different file with constants? Just move to regular one

2023-01-19 15:05 UTC, edchai approved these changes

2023-02-28 15:27 UTC, musienkoyuriy requested changes

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css-react-ssr/shell-apps/scss-tailwind-css/src/external.js
> +module.exports = () => {
do we need this?

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/combination-of-4/components/pages/consume-less-page.js
> +(
@belinef standalone jsx slice without assignment

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/combination-of-4/execute.js
> +const argv = JSON.parse(process.env.npm_config_argv);
possible exception here

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/any-combination/execute.js
> +const argv = JSON.parse(process.env.npm_config_argv);
@belinef  possible exception here

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/jss-and-tailwind-global/components/pages/consume-jss-page.js
> +(
@belinef also missed assignment

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/jss-and-tailwind-global/components/pages/consume-tailwind-global-css-page.js
> +(
@belinef also missed assignment

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/jss-css-and-tailwind-module/components/pages/consume-css-module-page.js
> +(
@belinef also missed assignment

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/jss-css-and-tailwind-module/components/pages/consume-jss-page.js
> +(
@belinef also missed assignment

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/jss-css-and-tailwind-module/components/pages/consume-tailwind-module-css-page.js
> +(
@belinef missed assignment

2023-02-28 15:27 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/less-and-styled-component/components/pages/consume-less-page.js
> +(
@belinef missed assignment

2023-03-01 06:26 UTC, belinef commented on federated-css/consumers-nextjs/less-and-styled-component/components/pages/consume-less-page.js
> +(
resolved

2023-03-01 06:27 UTC, belinef commented on federated-css/consumers-nextjs/jss-css-and-tailwind-module/components/pages/consume-tailwind-module-css-page.js
> +(
resolved

2023-03-01 06:27 UTC, belinef commented on federated-css/consumers-nextjs/jss-css-and-tailwind-module/components/pages/consume-jss-page.js
> +(
resolved

2023-03-01 06:27 UTC, belinef commented on federated-css/consumers-nextjs/jss-css-and-tailwind-module/components/pages/consume-css-module-page.js
> +(
resolved

2023-03-01 06:27 UTC, belinef commented on federated-css/consumers-nextjs/jss-and-tailwind-global/components/pages/consume-tailwind-global-css-page.js
> +(
resolved

2023-03-01 06:27 UTC, belinef commented on federated-css/consumers-nextjs/jss-and-tailwind-global/components/pages/consume-jss-page.js
> +(
resolved

2023-03-01 06:27 UTC, belinef commented on federated-css/consumers-nextjs/any-combination/execute.js
> +const argv = JSON.parse(process.env.npm_config_argv);
resolved

2023-03-01 06:28 UTC, belinef commented on federated-css/consumers-nextjs/any-combination/execute.js
> +const argv = JSON.parse(process.env.npm_config_argv);
so the exception will end the process with readable error during combination generation - i would like to believe this should be ok

2023-03-01 06:28 UTC, belinef commented on federated-css/consumers-nextjs/combination-of-4/execute.js
> +const argv = JSON.parse(process.env.npm_config_argv);
file removed - it's unnecessary

2023-03-01 06:29 UTC, belinef commented on federated-css/consumers-nextjs/combination-of-4/components/pages/consume-less-page.js
> +(
resolved

2023-03-01 06:29 UTC, belinef commented on federated-css-react-ssr/shell-apps/scss-tailwind-css/src/external.js
> +module.exports = () => {
removed

2023-03-16 14:00 UTC, musienkoyuriy requested changes

2023-03-16 14:00 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/boilerplates/consume-jss-page.js
> +(
missed assingment

2023-03-16 14:00 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/boilerplates/consume-scss-page.js
> +(
missed assignment

2023-03-16 14:00 UTC, musienkoyuriy commented on federated-css/consumers-nextjs/boilerplates/consume-tailwind-module-css-page.js
> +(
missed assignment

2023-03-16 14:00 UTC, musienkoyuriy commented on federated-css-react-ssr/shell-apps/less-scss/server/render.js
> +        console.log(styles);
unnecessary logging

2023-03-16 15:26 UTC, musienkoyuriy approved these changes

2023-03-16 16:32 UTC, zackarychapple commented
@ScriptedAlchemy ready for your review.

2023-03-17 13:27 UTC, merged