e2e-dynamic-remotes-runtime-refactoring
module-federation/module-federation-examples pull request #2595
Opened 2023-01-11 12:52 UTC by Andranik-mikhaielian

<img width="1536" alt="Screenshot 2023-01-11 at 4 52 29 PM" src="https://user-images.githubusercontent.com/78354418/211811131-5e377ab9-fd74-45f4-90d5-fb78ce9bde2c.png">

2023-01-11 14:13 UTC, PeaceDate commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +        buttonH2?: string,
isn't optional it used in both apps

2023-01-11 14:13 UTC, PeaceDate commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +        it (`Check host and Remote apps starts and running`, () => {
You can use here `property.subHeader`
Update please to use it `Check ${property.subheader} app start and running + check app elements`

2023-01-11 14:13 UTC, PeaceDate commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +            cy.wait(2000)
Do you really need this wait here?

2023-01-11 14:13 UTC, PeaceDate commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +            })
I think you don't need to similar methods one in if second in else
You can left one of them here

2023-01-12 16:02 UTC, PeaceDate approved these changes, later dismissed

2023-01-12 16:06 UTC, edchai requested changes

2023-01-12 16:06 UTC, edchai commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +        })
blankline after beforeEach

2023-01-12 16:06 UTC, edchai commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +        it (`Check ${property.subheader} app elements and application starts and running`, () => {
please provide less vague name then "starts and running"

2023-01-12 16:36 UTC, edchai requested changes

2023-01-12 16:36 UTC, edchai commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +
remove blankline

2023-01-12 16:36 UTC, edchai commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +
remove blankline, it should be only between beforeEach and it

2023-01-12 16:36 UTC, edchai commented on advanced-api/dynamic-remotes-runtime-environment-variables/e2e/checkDynamicRemotesRuntimesApps.cy.ts
> +
remove extra blankline

2023-01-13 08:23 UTC, edchai approved these changes, later dismissed

2023-01-13 08:54 UTC, ScriptedAlchemy approved these changes, later dismissed

2023-01-13 09:58 UTC, PeaceDate approved these changes

2023-01-13 10:01 UTC, edchai approved these changes

2023-01-13 21:07 UTC, merged