Added installation and start commang for all 3 apps
module-federation/module-federation-examples pull request #2635
Opened 2023-01-16 17:41 UTC by lexasq

2023-01-17 02:56 UTC, ScriptedAlchemy commented
is this ready for review?

2023-01-17 09:15 UTC, edchai approved these changes

2023-01-17 09:15 UTC, lexasq commented
> is this ready for review?

Yes, it should be ok by now.

2023-01-18 11:08 UTC, valorkin requested changes
use yarn --cwd

2023-01-18 11:08 UTC, valorkin commented
name convention ^

2023-01-18 14:18 UTC, valorkin commented on rollup-federation-demo/package.json
> +    "install:deps": "yarn install && yarn install:rollup && yarn install:rollup-rs && yarn install:webpack",
if you will use workspaces should not be just `yarn install`?

2023-01-18 14:19 UTC, lexasq commented on rollup-federation-demo/package.json
> +    "install:deps": "yarn install && yarn install:rollup && yarn install:rollup-rs && yarn install:webpack",
I wrote in the description that rollup can't resolve a dependency from parent folder in workspaces

2023-01-24 14:13 UTC, valorkin approved these changes

2023-01-29 13:53 UTC, ScriptedAlchemy commented
fix conflict pm pr

2023-01-30 08:44 UTC, closed without merging