e2e (nextjs-v12 sample)
module-federation/module-federation-examples pull request #2736
Opened 2023-02-06 18:39 UTC by Andranik-mikhaielian

<img width="1287" alt="Screenshot 2023-02-06 at 10 39 17 PM" src="https://user-images.githubusercontent.com/78354418/217057097-b6557b47-9d71-4dd2-9159-16be6157537a.png">

2023-02-07 08:37 UTC, PeaceDate commented
You've missed `vite-react-simple/e2e/tests/commonChecks.cy.ts` and `vite-react-simple/e2e/tests/viteAppChecks.cy.ts` during refactor of `openLocalhost()` method

2023-02-07 08:47 UTC, PeaceDate requested changes

2023-02-07 08:47 UTC, PeaceDate commented on cypress/fixtures/constants.ts
> +            gitButton: 'GitHub'
We already have these constants. Please check, what we have and use it

2023-02-07 08:47 UTC, PeaceDate commented on nextjs-v12/e2e/checkHomeApp.cy.ts
> +) => {
You can get rid of this duplicate constants.

2023-02-07 14:47 UTC, PeaceDate approved these changes

2023-02-07 15:32 UTC, edchai requested changes

2023-02-07 15:32 UTC, edchai commented on cypress/common/base.ts
> +            cy.visit(`${Cypress.env(`localhost${number}`)}/${path}`).wait(wait)
do not like the idea of wait with visit. Try use waitUntil with param something like "isWithWait" or just move wait to spec level

2023-02-07 15:32 UTC, edchai commented on cypress/fixtures/constants.ts
> +        nextJSv12: {
nextJSv12App

2023-02-07 15:32 UTC, edchai commented on cypress/fixtures/constants.ts
> +                buttonName: 'Federated Catch All',
name

2023-02-07 15:32 UTC, edchai commented on nextjs-v12/e2e/checkNextJSv12Apps.cy.ts
> +        appName: 'Checkout',
all appNames to constants

2023-02-07 15:32 UTC, edchai commented on nextjs-v12/e2e/checkNextJSv12Apps.cy.ts
> +        it (`Check application functionality and elements`, () => {
have no idea what is going on here. Better to split to multiple its with proper names

2023-02-07 15:32 UTC, edchai commented on nextjs-v12/package.json
> +  "devDependencies": {
as I understand we do not push major dependencies

2023-02-07 15:32 UTC, edchai commented on angular11-microfrontends-scully/e2e/checkAngular11SkullyApps.cy.ts
> +            path: '/product'
to constants -> hrefs

2023-02-08 16:25 UTC, edchai requested changes

2023-02-08 16:25 UTC, edchai commented on cypress/fixtures/constants.ts
> +        commonAngularData: {
strange place. If this link is used in only one place, this is not an app name as it supposed to be, if it used in multiple places -> move it to proper location inside commonConstantsData

2023-02-09 13:49 UTC, Andranik-mikhaielian commented on cypress/fixtures/constants.ts
> +        commonAngularData: {
It is used in a single place, so I renamed it in the constants.ts

2023-02-10 15:52 UTC, edchai approved these changes

2023-03-02 15:06 UTC, PeaceDate commented
Closed and reopen as a new PR ---> #2796

2023-03-02 15:07 UTC, PeaceDate commented
Closed and reopen as a new PR ---> https://github.com/module-federation/module-federation-examples/pull/2796

2023-03-02 15:07 UTC, closed without merging