Add e2e test for delegate-module and federated-npm
module-federation/module-federation-examples pull request #2739
Opened 2023-02-07 15:08 UTC by VladyslavZinchenko

![image](https://user-images.githubusercontent.com/58431266/217282315-b0c75365-d9b6-4be2-a0a9-56304a263824.png)
![image](https://user-images.githubusercontent.com/58431266/217282880-259aa150-8596-49ac-b2f5-a6ec340312e5.png)

2023-02-07 15:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/module-federation/module-federation-examples?pullRequest=2739) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/module-federation/module-federation-examples?pullRequest=2739) before we can accept your contribution.<br/><hr/>**Vladyslav Zinchenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/module-federation/module-federation-examples?pullRequest=2739) it.</sub>

2023-02-07 15:17 UTC, PeaceDate requested changes

2023-02-07 15:17 UTC, PeaceDate commented on delegate-modules/e2e/checkApplications.cy.ts
> +            host: number
You can left there only `appNameText` and `host`. Rest of attr you can use directly in your testcase

2023-02-07 15:17 UTC, PeaceDate commented on delegate-modules/e2e/checkApplications.cy.ts
> +    let appName = property.host === 3002 ? appsData[1].appNameText : appsData[0].appNameText;
It can be removed

2023-02-07 15:17 UTC, PeaceDate commented on federated-npm/e2e/checkApplications.cy.ts
> +            host: number
The same

2023-02-07 15:17 UTC, PeaceDate commented on federated-npm/e2e/checkApplications.cy.ts
> +        const host = property.host === 3001 ? appsData[0].host : property.host === 3002 ? appsData[1].host : appsData[2].host;
The same

2023-02-07 15:17 UTC, PeaceDate commented on delegate-modules/e2e/checkApplications.cy.ts
> +        it(`Check ${appName} built and running`, () => {
Make name of test more detailed

2023-02-07 15:17 UTC, PeaceDate commented on delegate-modules/e2e/checkApplications.cy.ts
> +        it(`Check buttons in ${appName} exist`, () => {
The same

2023-02-07 15:17 UTC, PeaceDate commented on federated-npm/e2e/checkApplications.cy.ts
> +        it(`Check ${appName} built and running`, () => {
The same

2023-02-07 15:17 UTC, PeaceDate commented on federated-npm/e2e/checkApplications.cy.ts
> +        it(`Check buttons in ${appName} exist`, () => {
The same

2023-02-07 15:34 UTC, edchai requested changes

2023-02-07 15:34 UTC, edchai commented on federated-npm/e2e/checkApplications.cy.ts
> +            basePage.checkElementWithTextPresence({
always check visibility if you can, visibilityState: 'be.visible'

2023-02-07 16:19 UTC, PeaceDate requested changes

2023-02-07 16:19 UTC, PeaceDate commented on delegate-modules/e2e/checkApplications.cy.ts
> +    let appName = property.host === 3002 ? appsData[1].appNameText : appsData[0].appNameText;
Forgot to remove

2023-02-07 16:19 UTC, PeaceDate commented on delegate-modules/e2e/checkApplications.cy.ts
> +let appsData = [
Use const

2023-02-07 16:19 UTC, PeaceDate commented on federated-npm/e2e/checkApplications.cy.ts
> +let appsData = [
Use const instead of let

2023-02-07 16:27 UTC, PeaceDate approved these changes

2023-02-08 09:28 UTC, edchai approved these changes

2023-02-08 10:07 UTC, merged